# Generated by Django 3.2.19 on 2023-06-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_minutes',
            field=models.IntegerField(blank=True),
        ),
    ]
