# Generated by Django 3.2.19 on 2023-06-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_time_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_minutes',
            field=models.IntegerField(),
        ),
    ]
